"""
Run the Phase 4 data quality checks against the loaded raw schema and
write a generated report to docs/data_quality_check_results.md.

Usage:
    python scripts/run_quality_checks.py

Exits with status 1 if any critical check fails (CI-friendly) — a
critical failure should block a staging rebuild, per
docs/data_quality_plan.md.
"""

import os
import sys
from datetime import datetime, timezone
from pathlib import Path

from dotenv import load_dotenv
from sqlalchemy import create_engine

sys.path.insert(0, str(Path(__file__).parent.parent / "src"))
from cassie.data.validation import run_all_checks, any_critical_failed  # noqa: E402

load_dotenv()

DATABASE_URL = os.environ.get("DATABASE_URL", "postgresql://cassie:cassie@localhost:5432/cassie")
REPORT_PATH = Path(__file__).parent.parent / "docs" / "data_quality_check_results.md"


def write_report(results, path: Path):
    lines = [
        "# Data Quality Check Results",
        "",
        "**Auto-generated by `scripts/run_quality_checks.py` — do not hand-edit.** "
        "For the narrative analysis (why these thresholds, what was tried and "
        "rejected, the cart-splitting and churn-window findings), see "
        "`docs/data_quality_report.md` and `docs/churn_definition.md`.",
        "",
        f"Run at: {datetime.now(timezone.utc).isoformat(timespec='seconds')}",
        "",
        "## Critical checks",
        "",
        "| Check | Violations | Status |",
        "|---|---|---|",
    ]
    for r in results:
        if r.severity != "critical":
            continue
        status = "PASS" if r.passed else "**FAIL**"
        lines.append(f"| {r.name} — {r.description} | {r.violation_count} | {status} |")

    lines += ["", "## Warning checks", "", "| Check | Violations | Status |", "|---|---|---|"]
    for r in results:
        if r.severity != "warning":
            continue
        status = "clean" if r.passed else f"{r.violation_count} flagged"
        lines.append(f"| {r.name} — {r.description} | {r.violation_count} | {status} |")

    overall = "FAIL — critical check(s) failed" if any_critical_failed(results) else "PASS"
    lines += ["", f"## Overall: {overall}", ""]

    path.write_text("\n".join(lines), encoding="utf-8")


def main():
    engine = create_engine(DATABASE_URL)
    print("Running data quality checks against raw.*...")
    results = run_all_checks(engine)

    for r in results:
        status = "PASS" if r.passed else "FAIL"
        marker = "[CRITICAL]" if r.severity == "critical" else "[warning] "
        print(f"  {marker} {status:4} {r.name} (violations: {r.violation_count})")

    write_report(results, REPORT_PATH)
    print(f"\nReport written to {REPORT_PATH}")

    if any_critical_failed(results):
        print("\nCRITICAL CHECK(S) FAILED — staging rebuild should not proceed.")
        sys.exit(1)
    else:
        print("\nAll critical checks passed.")
        sys.exit(0)


if __name__ == "__main__":
    main()
